import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { invoke } from "@tauri-apps/api/core";
import { useCptStore } from "../../store/useCptStore";
import "./ReportPreview.css";

/**
 * Section toggles in the report sidebar.
 *
 * For now these are visual-only — toggling them does NOT actually filter
 * the PDF output (the openaec generator doesn't yet expose a section-mask
 * API). The state is preserved so future PDF wiring is a one-line change.
 */
interface ReportSections {
  cover: boolean;
  coordTable: boolean;
  map: boolean;
  perCpt: boolean;
  sbtLegend: boolean;
  metadata: boolean;
}

const DEFAULT_SECTIONS: ReportSections = {
  cover: true,
  coordTable: true,
  map: true,
  perCpt: true,
  sbtLegend: false,
  metadata: false,
};

/**
 * PDF report preview — sidebar (section toggles + project info) + iframe.
 *
 * Renders the cached PDF bytes (pre-generated by `schedulePdfPreview`
 * from the store on doc open) for an instant preview. Falls back to a
 * live `preview_report` invoke if no cached entry exists, or refreshes
 * the cache if the bytes are missing for the current doc id.
 *
 * The sidebar lists which sections will appear in the generated PDF.
 * Section toggles are stored locally (component state) and not yet wired
 * to the openaec generator — they're a visual preview of an upcoming
 * filtering feature. The "Open project info" button dispatches a window
 * event so any container can open the ProjectSettingsDialog.
 */
export default function ReportPreview() {
  const { t } = useTranslation("ribbon");
  const cptsMap = useCptStore((s) => s.cpts);
  const cpts = useMemo(() => Array.from(cptsMap.values()), [cptsMap]);
  const projectMeta = useCptStore((s) => s.projectMeta);
  const activeDocId = useCptStore((s) => s.activeDocId);
  const cachedPdf = useCptStore((s) => (activeDocId ? s.pdfCache.get(activeDocId) : undefined));
  const setPdfCacheStore = useCptStore((s) => s.setPdfCache);

  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [sections, setSections] = useState<ReportSections>(DEFAULT_SECTIONS);

  // Track the active blob URL so we can revoke it on next render / unmount.
  const activeUrlRef = useRef<string | null>(null);

  useEffect(() => {
    if (cpts.length === 0) {
      if (activeUrlRef.current) {
        URL.revokeObjectURL(activeUrlRef.current);
        activeUrlRef.current = null;
      }
      setPdfUrl(null);
      setError(null);
      return;
    }

    // Fast path: cached PDF bytes for this doc are ready — display instantly.
    if (cachedPdf) {
      // Copy into a fresh Uint8Array<ArrayBuffer> — the cached buffer may be
      // typed as ArrayBufferLike (incl. SharedArrayBuffer) which Blob rejects.
      const copy = new Uint8Array(cachedPdf.length);
      copy.set(cachedPdf);
      const blob = new Blob([copy], { type: "application/pdf" });
      const url = URL.createObjectURL(blob);
      if (activeUrlRef.current) URL.revokeObjectURL(activeUrlRef.current);
      activeUrlRef.current = url;
      setPdfUrl(url);
      setLoading(false);
      setError(null);
      return;
    }

    // Cache miss — fall back to a live invoke and seed the cache afterwards.
    let cancelled = false;
    setLoading(true);
    setError(null);

    invoke<number[]>("preview_report", {
      cptIds: cpts.map((c) => c.id),
      project: projectMeta,
    })
      .then((bytes) => {
        if (cancelled) return;
        const u8 = new Uint8Array(bytes);
        const blob = new Blob([u8], { type: "application/pdf" });
        const url = URL.createObjectURL(blob);
        if (activeUrlRef.current) URL.revokeObjectURL(activeUrlRef.current);
        activeUrlRef.current = url;
        setPdfUrl(url);
        setLoading(false);
        // Seed the store cache so the next visit hits the fast path.
        if (activeDocId) setPdfCacheStore(activeDocId, u8);
      })
      .catch((e) => {
        if (cancelled) return;
        setError(String(e));
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [cpts, projectMeta, cachedPdf, activeDocId, setPdfCacheStore]);

  // Final cleanup on unmount.
  useEffect(() => {
    return () => {
      if (activeUrlRef.current) {
        URL.revokeObjectURL(activeUrlRef.current);
        activeUrlRef.current = null;
      }
    };
  }, []);

  const openProjectInfo = () => {
    window.dispatchEvent(new CustomEvent("ogs:open-project-settings"));
  };

  // Sidebar is always rendered (even when empty/error/loading) so the
  // user can still toggle sections / open project settings without first
  // having to load a CPT.
  const sidebar = (
    <aside className="report-sidebar">
      <div className="report-sidebar-header">
        <span className="report-sidebar-title">{t("report.sidebarTitle", "Rapport")}</span>
      </div>
      <div className="report-sidebar-body">
        {/* Project header */}
        <div className="report-project-summary">
          <div className="report-project-title">{projectMeta.title || t("report.untitled", "Naamloos project")}</div>
          {projectMeta.client && (
            <div className="report-project-sub">{projectMeta.client}</div>
          )}
          {projectMeta.location && (
            <div className="report-project-sub muted">{projectMeta.location}</div>
          )}
        </div>

        {/* Section toggles */}
        <div className="report-sidebar-section">
          <div className="report-sidebar-section-title">
            {t("report.sections", "Onderdelen")}
          </div>
          <div className="report-section-list">
            <SectionToggle label={t("report.section.cover", "Voorblad")}
              checked={sections.cover}
              onChange={(v) => setSections((s) => ({ ...s, cover: v }))} />
            <SectionToggle label={t("report.section.coordTable", "Coördinatentabel")}
              checked={sections.coordTable}
              onChange={(v) => setSections((s) => ({ ...s, coordTable: v }))} />
            <SectionToggle label={t("report.section.map", "Overzichtskaart")}
              checked={sections.map}
              onChange={(v) => setSections((s) => ({ ...s, map: v }))}
              hint={t("report.section.mapHint", "Pagina met alle sondeerlocaties op een kaart")} />
            <SectionToggle label={t("report.section.perCpt", "Per-sondering pagina's")}
              checked={sections.perCpt}
              onChange={(v) => setSections((s) => ({ ...s, perCpt: v }))} />
            <SectionToggle label={t("report.section.sbtLegend", "Robertson SBT legenda")}
              checked={sections.sbtLegend}
              onChange={(v) => setSections((s) => ({ ...s, sbtLegend: v }))}
              hint={t("report.section.sbtHint", "Aparte pagina met de 9 grondsoort-zones")} />
            <SectionToggle label={t("report.section.metadata", "Metadata-overzicht")}
              checked={sections.metadata}
              onChange={(v) => setSections((s) => ({ ...s, metadata: v }))}
              hint={t("report.section.metaHint", "Volledige #COMPANYID / #PROJECTID / kalibratie etc.")} />
          </div>
          <p className="report-sidebar-hint">
            {t("report.sectionsHint", "Aan/uit zetten van onderdelen wordt binnenkort actief.")}
          </p>
        </div>

        {/* CPT count */}
        <div className="report-sidebar-section">
          <div className="report-sidebar-meta">
            <div className="report-meta-row">
              <span className="report-meta-label">{t("report.cptCount", "Sonderingen")}</span>
              <span>{cpts.length}</span>
            </div>
          </div>
        </div>

        {/* Quick action — opens project settings via window event */}
        <div className="report-sidebar-section">
          <button
            type="button"
            className="report-sidebar-action"
            onClick={openProjectInfo}
            title={t("report.openProjectInfo", "Projectgegevens bewerken")}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 20h9" />
              <path d="M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z" />
            </svg>
            <span>{t("report.openProjectInfo", "Projectgegevens bewerken")}</span>
          </button>
        </div>
      </div>

      {/* Bottom: generate PDF action */}
      <div className="report-sidebar-footer">
        <button
          type="button"
          className="report-generate-btn-side"
          disabled={cpts.length === 0 || loading || !pdfUrl}
          onClick={() => {
            if (pdfUrl) window.open(pdfUrl, "_blank");
          }}
          title={t("report.openInNewWindow", "PDF openen in nieuw venster")}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
            <polyline points="14 2 14 8 20 8" />
            <line x1="9" y1="15" x2="15" y2="15" />
            <line x1="12" y1="12" x2="12" y2="18" />
          </svg>
          <span>{t("report.openPdf", "PDF openen")}</span>
        </button>
      </div>
    </aside>
  );

  // Render preview area with appropriate state.
  let previewArea: React.ReactNode;
  if (cpts.length === 0) {
    previewArea = (
      <div className="report-pages-wrapper">
        <div className="report-empty-state">
          <p className="report-empty-title">
            {t("report.noCpt", "Geen sonderingen geopend")}
          </p>
          <p className="report-empty-subtitle">
            {t("report.openCptHint", "Open een GEF of BRO-XML bestand om een rapport te genereren.")}
          </p>
        </div>
      </div>
    );
  } else if (error) {
    previewArea = (
      <div className="report-pages-wrapper">
        <div className="report-error">
          <p>{t("report.error", "Rapport-fout")}: {error}</p>
        </div>
      </div>
    );
  } else if (loading || !pdfUrl) {
    previewArea = (
      <div className="report-pages-wrapper">
        <div className="report-empty-state">
          <p className="report-empty-title">
            {t("report.generating", "Rapport genereren...")}
          </p>
        </div>
      </div>
    );
  } else {
    previewArea = (
      <div className="report-pages-wrapper">
        {/* PDF-viewer URL-fragment-params verbergen de toolbar +
            statusbar + zijpanel + page-labels die de Edge/Chrome
            ingebouwde PDF-reader tussen pagina's toont. `toolbar=0`
            = bovenste werkbalk uit, `navpanes=0` = thumbnails-side-
            panel uit, `statusbar=0` = onderbalk uit, `scrollbar=1`
            = scrollen blijft mogelijk, `view=FitH` = horizontaal
            inpassen (gebruiker-verzoek: geen "Page X" tekst meer
            tussen pagina's bij scrollen). */}
        <iframe
          src={`${pdfUrl}#toolbar=0&navpanes=0&statusbar=0&scrollbar=1&view=FitH&pagemode=none`}
          title={t("report.preview", "Rapport preview")}
          className="report-iframe"
        />
      </div>
    );
  }

  return (
    <div className="report-preview">
      {sidebar}
      <div className="report-main">
        {previewArea}
      </div>
    </div>
  );
}

function SectionToggle({
  label, checked, onChange, hint,
}: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  hint?: string;
}) {
  return (
    <label className="report-section-toggle" title={hint ?? "Filteren werkt nog niet — komt eraan"}>
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
      />
      <span>{label}</span>
    </label>
  );
}
